name: ax_flutter_util
description: A new Flutter project.
version: 3.0.0
homepage:

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
