name: ax_flutter_util
description: A new Flutter project.
version: 3.0.0
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  intl:  ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
